=== JoaoSantos497/IS/documentacao/tarefas.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "titulo": {
        "type": "string"
      },
      "descricao": {
        "type": "string"
      },
      "estado": {
        "type": "string",
        "enum": ["pendente", "em andamento", "conclu√≠da"]
      },
      "data_criacao": {
        "type": "string",
        "format": "date"
      },
      "data_limite": {
        "type": "string",
        "format": "date"
      }
    },
    "required": ["titulo", "descricao", "estado", "data_criacao", "data_limite"],
    "additionalProperties": false
  }

=== JoaoSantos497/IS/dados/tarefas.json
[
  {
    "titulo": "limpeza",
    "descricao": "limpar pratos",
    "estado": "pendente",
    "data_limite": "2025-05-02",
    "id": "dd4f3517-cc5b-486f-8c66-e4c390d11dea",
    "data_criacao": "2025-04-13"
  },
  {
    "id": "7a92ab75-83b9-4cee-9d60-81107d2f2512",
    "titulo": "Estudar gRPC",
    "descricao": "Ler documenta\u00e7\u00e3o e fazer testes",
    "estado": "pendente",
    "data_criacao": "2025-04-13",
    "data_limite": "2025-04-30"
  }
]
